settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 5002
  host: localhost
schema:
- name: airnote
  path: .
  commands:
    install:
      status: true
      method: go build -o airnote cmd/airnote/airnote.go
    run:
      status: true
      method: ./airnote
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
