version: '3.7'

services:
  api:
    image: airnote_dev
    build:
      context: ../../
      dockerfile: ./deployments/development/api/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ../../:/airnote
    depends_on:
      - db
      # - redis
    environment:
      MYSQL_DBNAME: airnote
      MYSQL_USER: airnote
      MYSQL_PASS: airnote
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_SKIPSQLCMD: "true"
      MYSQL_SSLMODE: "false"
      REDIS_HOST: redis
      REDIS_PORT: 6379
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: airnote
      MYSQL_USER: airnote
      MYSQL_PASSWORD: airnote
      MYSQL_ROOT_PASSWORD: airnote
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
  # redis:
  #   image: "redis:5.0.5-alpine"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
volumes:
  db-data:
    driver: local
  # redis-data:
  #   driver: local
