// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package rdb

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Links", testLinks)
	t.Run("LinksTags", testLinksTags)
	t.Run("Tags", testTags)
}

func TestDelete(t *testing.T) {
	t.Run("Links", testLinksDelete)
	t.Run("LinksTags", testLinksTagsDelete)
	t.Run("Tags", testTagsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Links", testLinksQueryDeleteAll)
	t.Run("LinksTags", testLinksTagsQueryDeleteAll)
	t.Run("Tags", testTagsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Links", testLinksSliceDeleteAll)
	t.Run("LinksTags", testLinksTagsSliceDeleteAll)
	t.Run("Tags", testTagsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Links", testLinksExists)
	t.Run("LinksTags", testLinksTagsExists)
	t.Run("Tags", testTagsExists)
}

func TestFind(t *testing.T) {
	t.Run("Links", testLinksFind)
	t.Run("LinksTags", testLinksTagsFind)
	t.Run("Tags", testTagsFind)
}

func TestBind(t *testing.T) {
	t.Run("Links", testLinksBind)
	t.Run("LinksTags", testLinksTagsBind)
	t.Run("Tags", testTagsBind)
}

func TestOne(t *testing.T) {
	t.Run("Links", testLinksOne)
	t.Run("LinksTags", testLinksTagsOne)
	t.Run("Tags", testTagsOne)
}

func TestAll(t *testing.T) {
	t.Run("Links", testLinksAll)
	t.Run("LinksTags", testLinksTagsAll)
	t.Run("Tags", testTagsAll)
}

func TestCount(t *testing.T) {
	t.Run("Links", testLinksCount)
	t.Run("LinksTags", testLinksTagsCount)
	t.Run("Tags", testTagsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Links", testLinksHooks)
	t.Run("LinksTags", testLinksTagsHooks)
	t.Run("Tags", testTagsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Links", testLinksInsert)
	t.Run("Links", testLinksInsertWhitelist)
	t.Run("LinksTags", testLinksTagsInsert)
	t.Run("LinksTags", testLinksTagsInsertWhitelist)
	t.Run("Tags", testTagsInsert)
	t.Run("Tags", testTagsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("LinksTagToLinkUsingLink", testLinksTagToOneLinkUsingLink)
	t.Run("LinksTagToTagUsingTag", testLinksTagToOneTagUsingTag)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("LinkToLinksTags", testLinkToManyLinksTags)
	t.Run("TagToLinksTags", testTagToManyLinksTags)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("LinksTagToLinkUsingLinksTags", testLinksTagToOneSetOpLinkUsingLink)
	t.Run("LinksTagToTagUsingLinksTags", testLinksTagToOneSetOpTagUsingTag)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("LinkToLinksTags", testLinkToManyAddOpLinksTags)
	t.Run("TagToLinksTags", testTagToManyAddOpLinksTags)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Links", testLinksReload)
	t.Run("LinksTags", testLinksTagsReload)
	t.Run("Tags", testTagsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Links", testLinksReloadAll)
	t.Run("LinksTags", testLinksTagsReloadAll)
	t.Run("Tags", testTagsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Links", testLinksSelect)
	t.Run("LinksTags", testLinksTagsSelect)
	t.Run("Tags", testTagsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Links", testLinksUpdate)
	t.Run("LinksTags", testLinksTagsUpdate)
	t.Run("Tags", testTagsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Links", testLinksSliceUpdateAll)
	t.Run("LinksTags", testLinksTagsSliceUpdateAll)
	t.Run("Tags", testTagsSliceUpdateAll)
}
