// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package rdb

var TableNames = struct {
	Links     string
	LinksTags string
	Tags      string
}{
	Links:     "links",
	LinksTags: "links_tags",
	Tags:      "tags",
}
